//Enum Roles
export const Roles = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN_KEUANGAN: "ADMIN_KEUANGAN",
  OPERATOR_KEUANGAN: "OPERATOR_KEUANGAN",
  KASUBAG_KEUANGAN: "KASUBAG_KEUANGAN",
  KEPALA_TU_FAKULTAS: "KEPALA_TU_FAKULTAS",
  WAKIL_DEKAN_2: "WAKIL_DEKAN_2",
  WAKIL_REKTOR_2: "WAKIL_REKTOR_2",
  REKTOR: "REKTOR",
};
